version: '3.8'

services:
  java-app:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - app-target:/app/target
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: speeddating
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7f7YP2O6j62khQBcTOx
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservice_network

  react-app:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    depends_on:
      - java-app
volumes:
  app-target:
  postgres-data:


networks:
  microservice_network:
    driver: bridge
